# ──────────────────────────────────────────────
# Stage 1: Install dependencies
# ──────────────────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
# ci installs exact versions from package-lock.json — reproducible builds
RUN npm ci

# ──────────────────────────────────────────────
# Stage 2: Build the Next.js app
# ──────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# DOCKER_BUILD=true enables output:"standalone" in next.config.ts,
# producing a self-contained build in .next/standalone.
RUN DOCKER_BUILD=true npm run build

# ──────────────────────────────────────────────
# Stage 3: Minimal production image
# ──────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

# standalone output includes only what's needed to run the server
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

# server.js is the entrypoint generated by Next.js standalone output
CMD ["node", "server.js"]
